version: '3.3'

services:
  client-webpage:
    container_name: client-webpage
    # image: client-webpage:latest
    build: ./
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"